### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by johnoliver42** [johnoliver42/The-Java-Collective#1]
@pawaitemadisoncollege  Week 1 deliverables

**Comment by pawaitemadisoncollege** [comment]
@johnoliver42 @AliviaK @e-christenson  Your team has a very nice start here with a full listing of the strengths and skill each team members brings to your group, and thoughtful charter. 

Suggestions:

 - [ ] If there are developer-environment-specific config or property files that should not be shared, consider adding them to .gitignore sooner than later.
 - [ ] Keep in mind your primary goal is to build a RESTful API, so Bootstrap and Bootstrap validator may not be essential to the project. Though this may lead into a discussion about if/how your service might validate incoming data and what error responses you might use.

**Comment by johnoliver42** [comment]
Sorry, I forgot to reply to this sooner. We have addressed all of these issues.
